version: '3.8'
services:
  my-app:
    build: ./
    command: /app/main
    ports:
     - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres
  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: 'taskdb'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres


networks:
  postgres:
    driver: bridge